name: Docker CI

on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: "Docker build and push"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=date::$(date +%Y-%m-%d)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: "Build docker image PROD"
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: docker build -t ghcr.io/marigold-dev/decookies:latest .
      - name: "Build docker image NPR"
        if: contains(github.event.pull_request.labels.*.name, 'docker')
        run: docker build -t ghcr.io/marigold-dev/decookies:latest .
      - name: "Re-tag image"
        if: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') ||  contains(github.event.pull_request.labels.*.name, 'docker')}}
        run: |
          docker image tag ghcr.io/marigold-dev/decookies:latest ghcr.io/marigold-dev/decookies:stable
          docker image tag ghcr.io/marigold-dev/decookies:latest ghcr.io/marigold-dev/decookies:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
          docker image tag ghcr.io/marigold-dev/decookies:latest ghcr.io/marigold-dev/decookies:pr-${{ github.event.number }}-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
      - name: "Push image"
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: |
          docker image push ghcr.io/marigold-dev/decookies:stable
          docker image push ghcr.io/marigold-dev/decookies:latest
          docker image push ghcr.io/marigold-dev/decookies:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
      - name: "Push image for PR"
        # Run this if the PR has the "docker" label
        if: contains(github.event.pull_request.labels.*.name, 'docker')
        run: |
          docker image push ghcr.io/marigold-dev/decookies:latest
          docker image push ghcr.io/marigold-dev/decookies:pr-${{ github.event.number }}-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
