name: Docker CI

on:
  push:
    branches:
      - feat/dekuV1
      - feat/dekuWASM

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: "Docker build and push"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=date::$(date +%Y-%m-%d)"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: "Build Deku-P"
        if: ${{ github.ref == 'refs/heads/feat/dekuV1' }}
        run: docker build -t ghcr.io/marigold-dev/decookies-p:latest .
      - name: "Build Deku-C"
        if: ${{ github.ref == 'refs/heads/feat/dekuWASM' }}
        run: docker build -t ghcr.io/marigold-dev/decookies-c:latest .
      - name: "Re-tag image Deku-p"
        if: ${{ github.ref == 'refs/heads/feat/dekuV1'}}
        run: |
          docker image tag ghcr.io/marigold-dev/decookies-p:latest ghcr.io/marigold-dev/decookies-p:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
          docker image tag ghcr.io/marigold-dev/decookies-p:latest ghcr.io/marigold-dev/decookies-p:pr-${{ github.event.number }}-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
      - name: "Re-tag image Deku-c"
        if: ${{ github.ref == 'refs/heads/feat/dekuWASM'}}
        run: |
          docker image tag ghcr.io/marigold-dev/decookies-c:latest ghcr.io/marigold-dev/decookies-c:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
          docker image tag ghcr.io/marigold-dev/decookies-c:latest ghcr.io/marigold-dev/decookies-c:pr-${{ github.event.number }}-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
      - name: "Push image Deku-c"
        if: ${{ github.ref == 'refs/heads/feat/dekuV1' }}
        run: |
          docker image push ghcr.io/marigold-dev/decookies-p:latest
          docker image push ghcr.io/marigold-dev/decookies-p:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
      - name: "Push image Deku-p"
        if: ${{ github.ref == 'refs/heads/feat/dekuWASM' }}
        run: |
          docker image push ghcr.io/marigold-dev/decookies-c:latest
          docker image push ghcr.io/marigold-dev/decookies-c:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
